name: conoce_bonao
description: Conoce Bonao App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  get: ^4.6.5
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  flutter_spinkit: ^5.1.0  
  synchronized: ^3.0.0+2
  flutter_credit_card: ^3.0.1
  select_dialog: ^2.0.0
  flutter_local_notifications: ^9.7.0
  firebase_messaging: ^12.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  readmore: ^2.2.0
  photo_view: ^0.14.0
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.1.9
  location: ^4.4.0
  flutter_rating_bar: ^4.0.1
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.5
  rxdart: ^0.27.5
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner:
  flutter_gen_runner:
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ecotourism/
    - assets/images/carousel/
    - assets/images/hotels/
    - assets/images/hotels/photos/
    - assets/images/restaurants/
    - assets/images/restaurants/photos/
    - assets/icons/
    # - assets/icons/2.0x/
    - assets/json/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
